### ISSUE TITLE
IndexError: The shape of the mask [384, 19] at index 0 does not match the shape of the indexed tensor [9216, 19] at index 0

### ISSUE THREAD

**Issue by BastianChen** [michaeltrs/DeepSatModels#3] opened 2023-03-13 06:09 UTC
Hi,
When I run the segmentation_training_transf.py, there is an error: IndexError: The shape of the mask [384, 19] at index 0 does not match the shape of the indexed tensor [9216, 19] at index 0：

![image](https://user-images.githubusercontent.com/31885291/224620931-3d03fd4e-5121-4d6a-9659-95491d1e4fcf.png)

The shape of the mask is [16,24,19].Is there a problem with the mask shape?

**Comment by michaeltrs** [comment] 2023-03-14 20:11
Hi @CChBen,

For semantic segmentation the role of the mask is to zero-out the effect of some spatial locations from the loss function and performance metrics. Possible such locations could be ones that contain a class we are not interested in predicting or a location we suspect might have a noisy label.

To do this we need a 2D mask. Assuming your batch size is 16 and you are using size 24x24 samples, the mask should have dimensions 16x24x24 straight out of the dataloader. The loss function further [reshapes the mask to 16\*24\*24x1](https://github.com/michaeltrs/DeepSatModels/blob/abad503d1143401a573f5e1bf8c972bc9dadea49/metrics/loss_functions.py#L184) and [repeats it over the last dimension equal to the number of classes](https://github.com/michaeltrs/DeepSatModels/blob/abad503d1143401a573f5e1bf8c972bc9dadea49/metrics/loss_functions.py#L187) (assume 19) to size 16\*24\*24x19 (that should have been the mask size instead of 16\*24x19) that is used to select logits only from the locations of interest. My guess is that at some point a spatial dimension in either the mask or labels has collapsed.

**Comment by June01** [comment] 2023-03-15 13:00
Hey, I met the same problem when running the code, and fix this issue by the following modification in https://github.com/michaeltrs/DeepSatModels/blob/abad503d1143401a573f5e1bf8c972bc9dadea49/data/PASTIS24/data_transforms.py#L65
to
```
tensor_sample['labels'] = torch.tensor(sample['labels'].astype(np.float32)).to(torch.float32)
```

Hope it helps.

**Comment by michaeltrs** [comment] 2023-03-15 20:30
@June01, @CChBen did you get this error using the PASTIS24 data?

**Comment by June01** [comment] 2023-03-16 02:34
> @June01, @CChBen did you get this error using the PASTIS24 data?

Hi @michaeltrs , yes. I think it is nicer to be fixed in your original repo.

**Comment by michaeltrs** [comment] 2023-03-16 10:21
Thanks @June01 ! 

Can you provide some extra details to help me understand what the issue is because I can't directly replicate the error using PASTIS24. 

Did you get the error from the first sample or does it occur at some point during training? 

Also, could you please check what is the PASTIS24 sample['labels'] size just by reading the file w/o transforms? 
```
spath = '**/*.pickle'   # path to a .pickle file in PASTIS24 
with open(spath, 'rb') as handle:
    sample = pickle.load(handle, encoding='latin1')
    print(sample['labels'].shape)
```
It should be 3x24x24.

**Comment by June01** [comment] 2023-03-16 10:30
> Thanks @June01 !
> 
> Can you provide some extra details to help me understand what the issue is because I can't directly replicate the error using PASTIS24.
> 
> Did you get the error from the first sample or does it occur at some point during training?
> 
> Also, could you please check what is the PASTIS24 sample['labels'] size just by reading the file w/o transforms?
> 
> ```
> spath = '**/*.pickle'   # path to a .pickle file in PASTIS24 
> with open(spath, 'rb') as handle:
>     sample = pickle.load(handle, encoding='latin1')
>     print(sample['labels'].shape)
> ```
> 
> It should be 3x24x24.

Hi @michaeltrs , here it is. I guess it is the problem of python version maybe, mine is 3.7.13.

![image](https://user-images.githubusercontent.com/12269592/225589150-9fdafd1f-4167-48ea-9128-19ee70f1fcaa.png)

**Comment by BastianChen** [comment] 2023-03-16 12:18
> Hey, I met the same problem when running the code, and fix this issue by the following modification in
> 
> https://github.com/michaeltrs/DeepSatModels/blob/abad503d1143401a573f5e1bf8c972bc9dadea49/data/PASTIS24/data_transforms.py#L65
> 
> 
> to
> ```
> tensor_sample['labels'] = torch.tensor(sample['labels'].astype(np.float32)).to(torch.float32)
> ```
> 
> Hope it helps.

Hi @June01 ,it works.Thanks for your help.

**Comment by BastianChen** [comment] 2023-03-16 12:22
> Thanks @June01 !
> 
> Can you provide some extra details to help me understand what the issue is because I can't directly replicate the error using PASTIS24.
> 
> Did you get the error from the first sample or does it occur at some point during training?
> 
> Also, could you please check what is the PASTIS24 sample['labels'] size just by reading the file w/o transforms?
> 
> ```
> spath = '**/*.pickle'   # path to a .pickle file in PASTIS24 
> with open(spath, 'rb') as handle:
>     sample = pickle.load(handle, encoding='latin1')
>     print(sample['labels'].shape)
> ```
> 
> It should be 3x24x24.

Hi @michaeltrs ,my output shape is also (24,24) and my python version is 3.10.6.

**Closed as completed** 2023-04-14 11:36 UTC
